### ISSUE TITLE
MeshTool Crashes on Linux, Cannot Find Resource Files on OS X

### ISSUE THREAD

**Issue by ghost** [JaviCervera/vortex#2]
When built for OS X, MeshTool is unable to find the resources files needed from the /data folder. 

When built for Linux, MeshTool always causes segfault errors when trying to load simple mesh files. I've tried to load Wavefront OBJ files as well as IrrMesh files without success.

**Comment by JaviCervera** [comment]
I don't have the problem with OS X, I will try to reproduce it.

With Linux, yes, I have noticed the segfault, and will look into it.

**Comment by JaviCervera** [comment]
Should be fixed on Vortex2 beta.
