### ISSUE TITLE
Request: Need a function to pick 3d objects

### ISSUE THREAD

**Issue by MikeHart66** [JaviCervera/vortex#3]
Hi Javi,

is there a function where you can pick 3D objects under a specified 2D coordinate of your camera view? And set objects to be not pickable?

**Comment by JaviCervera** [comment]
Sorry! Missed this. It will be added!

**Comment by MikeHart66** [comment]
Any news about this?

**Comment by JaviCervera** [comment]
I started a picking sample, but there's not been much development in the Vortex front since the release of beta2. It didn't seem to caught much attention upon release. Is Cerberus-X gaining traction? How active is it?

**Comment by MikeHart66** [comment]
Not much. I can understand if you see no reason to continue.
