### ISSUE TITLE
Texture doesn't show up in HTML5

### ISSUE THREAD

**Issue by MikeHart66** [JaviCervera/vortex#5]
Hi Javi,

I discovered that a texture doesn't show up in HTML5. Please look at the base.

![image](https://user-images.githubusercontent.com/1486388/54878143-b8f17100-4e28-11e9-8547-cdf184823a5b.png)

**Comment by JaviCervera** [comment]
Which format is the texture in? It could be due to the way textures are loaded by the gles20 target on different platforms.
