### ISSUE TITLE
Request: LookAt method

### ISSUE THREAD

**Issue by MikeHart66** [JaviCervera/vortex#6]
Hi Javi,

it would be cool if Vortex would have a entity.LookAt(entity) method. So for an example, the camera could always look at a certain entity.

Cheers
Michael

**Comment by JaviCervera** [comment]
That one's easy to add. I am doing that on meshtool to orient the light in the direction the camera is facing, but it was done with math functions and I didn't add a fancy LookAt method. I'll add it, so it will be in the next commit to the develop branch.
