### ISSUE TITLE
Request: TurnTo method

### ISSUE THREAD

**Issue by MikeHart66** [JaviCervera/vortex#7]
Hi Javi,

it would be cool if Vortex would have a entity.TurnToEntity (targetEntity,xrate,yrate,zrate) method. So for an example, the camera could turn to at a certain entity.

Cheers
Michael

**Comment by JaviCervera** [comment]
I probably won't add it as part of the core engine, but I could write a sample and write a function in there.

**Comment by MikeHart66** [comment]
If you think there not enough attention towards vortex then don't bother.
