### ISSUE TITLE
Lighning and shadow issues in release2.0 branch

### ISSUE THREAD

**Issue by MikeHart66** [JaviCervera/vortex#9]
Hi Javi,

running the test_lighning show no lightning, just white circles. In the test_shadow example  no shadows with the latest code you pushed. The test_specular has no reflection to show, only an yellow circle. The hoverbike and robot demo are also broken.

Cheers
Michael

**Comment by JaviCervera** [comment]
Hi Mike. Sorry for the late response. I have mail notifications enabled, but I don’t know if they are going to the junk mail folder, because I missed this. Which target are you running it on? I am not able to reproduce the problems you mention on Desktop (macOS Big Sur) nor HTML5.

**Comment by MikeHart66** [comment]
Windows

**Comment by MikeHart66** [comment]
Just tested this on Windows with the html5 and glfw target.

test_shadows -> no shadows what so ever
test-spectacular -> on glfw you can't set the shininess
demo_hoverbike -> you can't switch the shader
demo_robot -> way too bright, you hardly can see the shader changing. So no spectacularity on the robot visible.

![image](https://user-images.githubusercontent.com/1486388/118401878-b5a04b80-b667-11eb-9984-b8fdec31dc31.png)

![image](https://user-images.githubusercontent.com/1486388/118401905-d23c8380-b667-11eb-85c9-b69fb12b11e2.png)

**Comment by JaviCervera** [comment]
Ok, I've got different results on different platforms on the way stuff is rendered. I made some changes to the shaders implementation in the last commits, so I will take a look to verify what has broken the implementation.

**Comment by JaviCervera** [comment]
I have moved the problematic changes out of the release/2.0 branch, since there were some changes to the shaders causing the problems that I have decided to postpone to 2.1.

So I am (finally!) putting 2.0 in feature-freeze and will work on code cleanup and documentation before the public final release.

**Comment by MikeHart66** [comment]
Great to hear. Thank you for looking into this.
